// Made by Jack (iamjustjack.de)

import { writeFileSync } from 'node:fs';

type Sides = { top: number; right: number; bottom: number; left: number };
type Shape = { name: string; seed: number; step: number; sides: Sides };

const SHAPES: Shape[] = [
  { name: 'top-2', seed: 11, step: 1.6, sides: { top: 1.8, right: 0, bottom: 0, left: 0 } },
  { name: 'bottom-1', seed: 21, step: 1.6, sides: { top: 0, right: 0, bottom: 1.8, left: 0 } },
  { name: 'bottom-2', seed: 22, step: 1.4, sides: { top: 0, right: 0, bottom: 3, left: 0 } },
  { name: 'tb-1', seed: 31, step: 1.5, sides: { top: 1.6, right: 0, bottom: 1.6, left: 0 } },
  { name: 'foot-1', seed: 41, step: 1.2, sides: { top: 6, right: 0, bottom: 0, left: 0 } },
  { name: 'card-4', seed: 51, step: 2.6, sides: { top: 3, right: 2.2, bottom: 3, left: 2.2 } },
  { name: 'card-5', seed: 52, step: 2.4, sides: { top: 2.6, right: 2.6, bottom: 2.6, left: 2.6 } },
  { name: 'chip-1', seed: 61, step: 4, sides: { top: 6, right: 3, bottom: 6, left: 3 } },
  { name: 'chip-2', seed: 62, step: 4, sides: { top: 7, right: 2.5, bottom: 7, left: 2.5 } },
  { name: 'r-1', seed: 71, step: 3, sides: { top: 0, right: 4, bottom: 0, left: 0 } },
  { name: 'l-2', seed: 72, step: 3, sides: { top: 0, right: 0, bottom: 0, left: 4 } },
];

function mulberry32(seed: number) {
  return () => {
    seed |= 0;
    seed = (seed + 0x6d2b79f5) | 0;
    let t = Math.imul(seed ^ (seed >>> 15), 1 | seed);
    t = (t + Math.imul(t ^ (t >>> 7), 61 | t)) ^ t;
    return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
  };
}

const f = (n: number) => `${Math.min(100, Math.max(0, n)).toFixed(1)}%`;

function polygon(shape: Shape, inner: boolean, rand: () => number): string {
  const pts: string[] = [];
  const depth = (amp: number) => {
    if (!amp) return 0;
    return inner ? amp * (0.45 + rand() * 1.25) : amp * rand();
  };
  const walk = (amp: number, emit: (t: number, d: number) => void) => {
    if (!amp) return emit(0, 0);
    for (let t = 0; t < 100; t += shape.step * (0.6 + rand() * 0.8)) emit(t, depth(amp));
  };
  const { top, right, bottom, left } = shape.sides;
  walk(top, (t, d) => pts.push(`${f(t)} ${f(d)}`));
  walk(right, (t, d) => pts.push(`${f(100 - d)} ${f(t)}`));
  walk(bottom, (t, d) => pts.push(`${f(100 - t)} ${f(100 - d)}`));
  walk(left, (t, d) => pts.push(`${f(d)} ${f(100 - t)}`));
  return `polygon(${pts.join(',')})`;
}

const css = SHAPES.map((s) => {
  const rand = mulberry32(s.seed);
  return `.pp-t-${s.name}{--co:${polygon(s, false, rand)};--ci:${polygon(s, true, rand)}}`;
});

writeFileSync(
  new URL('../src/styles/torn-generated.css', import.meta.url),
  `/* Made by Jack. Generated by scripts/torn.ts - do not edit by hand. */\n${css.join('\n')}\n`,
);
console.log(`torn: wrote ${SHAPES.length} shapes`);
